{{- if .Values.configMaps.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "versions.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "versions.labels" . | nindent 4 }}
    app: {{ include "versions.name" . }}
  annotations:
    'strategy.spinnaker.io/max-version-history': '3'
data:
{{ .Values.configMaps.contents | indent 2 }}
{{- end -}}