{{- if .Values.hpa.enabled -}}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "versions.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "versions.labels" . | nindent 4 }}
    app: {{ include "versions.name" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "versions.name" . }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ .Values.hpa.metrics.utilization.cpu }}
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: {{ .Values.hpa.metrics.utilization.memory }}
{{- end -}}