apiVersion: v1
kind: Service
metadata:
  name: {{ include "versions.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "versions.labels" . | nindent 4 }}
    app: {{ include "versions.name" . }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  {{- if .Values.metrics.serviceMonitor.app.enabled }}
  - port: {{ .Values.metrics.serviceMonitor.app.port }}
    targetPort: metrics
    protocol: TCP
    name: metrics
  {{- end }}
  selector:
    {{- include "versions.selectorLabels" . | nindent 4 }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end -}}